/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baldesDeTinta;

import java.awt.Color;

/**
 *
 * @author Farias
 */
public class jframePrincipal extends javax.swing.JFrame {
    String hex = "#";
    //MisturadorDeCores mistura = new MisturadorDeCores();
    /**
     * Creates new form jframePrincipal
     */
    public jframePrincipal() 
    {
        initComponents();
    }
    
    public String RGBToHex(int r, int g, int b)
    {
        hex = "#";
        if(r<16)
            hex += '0' + Integer.toHexString(r);
        else
            hex +=       Integer.toHexString(r);
        if(g<16)
            hex += '0' + Integer.toHexString(g);
        else
            hex +=       Integer.toHexString(g);
        if(b<16)
            hex += '0' + Integer.toHexString(b);
        else
            hex +=       Integer.toHexString(b);
        return hex.toUpperCase();
    }
    private void Atualizar()
    {//Cor 1
        txtR1.setText(String.valueOf(sldR1.getValue()));
        txtG1.setText(String.valueOf(sldG1.getValue()));
        txtB1.setText(String.valueOf(sldB1.getValue()));
        txtRGB1.setText(RGBToHex(sldR1.getValue(), sldG1.getValue(), sldB1.getValue()));
        pnl1.setBackground(new Color(sldR1.getValue(),sldG1.getValue(),sldB1.getValue()));
    //Cor 2
        txtR2.setText(String.valueOf(sldR2.getValue()));
        txtG2.setText(String.valueOf(sldG2.getValue()));
        txtB2.setText(String.valueOf(sldB2.getValue()));
        txtRGB2.setText(RGBToHex(sldR2.getValue(), sldG2.getValue(), sldB2.getValue()));
        pnl2.setBackground(new Color(sldR2.getValue(),sldG2.getValue(),sldB2.getValue()));
    //Cor final    
        txtRR.setText(String.valueOf((sldR1.getValue() + sldR2.getValue())/2));
        txtGR.setText(String.valueOf((sldG1.getValue() + sldG2.getValue())/2));
        txtBR.setText(String.valueOf((sldB1.getValue() + sldB2.getValue())/2));
        sldRR.setValue(Integer.parseInt(txtRR.getText()));
        sldGR.setValue(Integer.parseInt(txtGR.getText()));
        sldBR.setValue(Integer.parseInt(txtBR.getText()));
        pnlR.setBackground(new Color(sldRR.getValue(),sldGR.getValue(),sldBR.getValue()));
        txtRGBR.setText(RGBToHex(sldRR.getValue(), sldGR.getValue(), sldBR.getValue()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();
        txtRGB1 = new javax.swing.JTextField();
        txtR1 = new javax.swing.JTextField();
        btnR1Menos = new javax.swing.JButton();
        sldR1 = new javax.swing.JSlider();
        lblR1 = new javax.swing.JLabel();
        sldG1 = new javax.swing.JSlider();
        lblG1 = new javax.swing.JLabel();
        btnG1Menos = new javax.swing.JButton();
        txtG1 = new javax.swing.JTextField();
        sldB1 = new javax.swing.JSlider();
        lblB1 = new javax.swing.JLabel();
        btnB1Menos = new javax.swing.JButton();
        txtB1 = new javax.swing.JTextField();
        btnR1Mais = new javax.swing.JButton();
        btnG1Mais = new javax.swing.JButton();
        btnB1Mais = new javax.swing.JButton();
        btnB3Mais = new javax.swing.JButton();
        sldR2 = new javax.swing.JSlider();
        lblR2 = new javax.swing.JLabel();
        btnR2Menos = new javax.swing.JButton();
        sldG2 = new javax.swing.JSlider();
        lblG2 = new javax.swing.JLabel();
        btnG2Menos = new javax.swing.JButton();
        txtG2 = new javax.swing.JTextField();
        sldB2 = new javax.swing.JSlider();
        lblB2 = new javax.swing.JLabel();
        btnB2Menos = new javax.swing.JButton();
        txtB2 = new javax.swing.JTextField();
        btnR2Mais = new javax.swing.JButton();
        txtRGB2 = new javax.swing.JTextField();
        btnG2Mais = new javax.swing.JButton();
        pnl2 = new javax.swing.JPanel();
        txtR2 = new javax.swing.JTextField();
        sldRR = new javax.swing.JSlider();
        lblRR = new javax.swing.JLabel();
        sldGR = new javax.swing.JSlider();
        lblGR = new javax.swing.JLabel();
        txtGR = new javax.swing.JTextField();
        sldBR = new javax.swing.JSlider();
        lblBR = new javax.swing.JLabel();
        txtBR = new javax.swing.JTextField();
        txtRGBR = new javax.swing.JTextField();
        pnlR = new javax.swing.JPanel();
        txtRR = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Baldes de Tinta");
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        setResizable(false);

        pnl1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );

        txtRGB1.setEditable(false);
        txtRGB1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtRGB1.setText("#FFFFFF");

        txtR1.setEditable(false);
        txtR1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtR1.setText("255");
        txtR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtR1ActionPerformed(evt);
            }
        });

        btnR1Menos.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnR1Menos.setText("-");
        btnR1Menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnR1MenosActionPerformed(evt);
            }
        });

        sldR1.setMaximum(255);
        sldR1.setOrientation(javax.swing.JSlider.VERTICAL);
        sldR1.setValue(255);
        sldR1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sldR1MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                sldR1MouseMoved(evt);
            }
        });
        sldR1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sldR1MouseClicked(evt);
            }
        });
        sldR1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                sldR1PropertyChange(evt);
            }
        });

        lblR1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lblR1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblR1.setText("R");

        sldG1.setMaximum(255);
        sldG1.setOrientation(javax.swing.JSlider.VERTICAL);
        sldG1.setValue(255);
        sldG1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sldG1MouseDragged(evt);
            }
        });
        sldG1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sldG1MouseClicked(evt);
            }
        });

        lblG1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lblG1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblG1.setText("G");

        btnG1Menos.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnG1Menos.setText("-");
        btnG1Menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG1MenosActionPerformed(evt);
            }
        });

        txtG1.setEditable(false);
        txtG1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtG1.setText("255");

        sldB1.setMaximum(255);
        sldB1.setOrientation(javax.swing.JSlider.VERTICAL);
        sldB1.setValue(255);
        sldB1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sldB1MouseDragged(evt);
            }
        });
        sldB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sldB1MouseClicked(evt);
            }
        });

        lblB1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lblB1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblB1.setText("B");

        btnB1Menos.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnB1Menos.setText("-");
        btnB1Menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB1MenosActionPerformed(evt);
            }
        });

        txtB1.setEditable(false);
        txtB1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtB1.setText("255");

        btnR1Mais.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnR1Mais.setText("+");
        btnR1Mais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnR1MaisActionPerformed(evt);
            }
        });

        btnG1Mais.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnG1Mais.setText("+");
        btnG1Mais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG1MaisActionPerformed(evt);
            }
        });

        btnB1Mais.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnB1Mais.setText("+");
        btnB1Mais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB1MaisActionPerformed(evt);
            }
        });

        btnB3Mais.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnB3Mais.setText("+");
        btnB3Mais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB3MaisActionPerformed(evt);
            }
        });

        sldR2.setMaximum(255);
        sldR2.setOrientation(javax.swing.JSlider.VERTICAL);
        sldR2.setValue(255);
        sldR2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sldR2MouseDragged(evt);
            }
        });
        sldR2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sldR2MouseClicked(evt);
            }
        });

        lblR2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lblR2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblR2.setText("R");

        btnR2Menos.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnR2Menos.setText("-");
        btnR2Menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnR2MenosActionPerformed(evt);
            }
        });

        sldG2.setMaximum(255);
        sldG2.setOrientation(javax.swing.JSlider.VERTICAL);
        sldG2.setValue(255);
        sldG2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sldG2MouseDragged(evt);
            }
        });
        sldG2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sldG2MouseClicked(evt);
            }
        });

        lblG2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lblG2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblG2.setText("G");

        btnG2Menos.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnG2Menos.setText("-");
        btnG2Menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG2MenosActionPerformed(evt);
            }
        });

        txtG2.setEditable(false);
        txtG2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtG2.setText("255");

        sldB2.setMaximum(255);
        sldB2.setOrientation(javax.swing.JSlider.VERTICAL);
        sldB2.setValue(255);
        sldB2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sldB2MouseDragged(evt);
            }
        });
        sldB2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sldB2MouseClicked(evt);
            }
        });

        lblB2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lblB2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblB2.setText("B");

        btnB2Menos.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnB2Menos.setText("-");
        btnB2Menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB2MenosActionPerformed(evt);
            }
        });

        txtB2.setEditable(false);
        txtB2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtB2.setText("255");

        btnR2Mais.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnR2Mais.setText("+");
        btnR2Mais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnR2MaisActionPerformed(evt);
            }
        });

        txtRGB2.setEditable(false);
        txtRGB2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtRGB2.setText("#FFFFFF");

        btnG2Mais.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnG2Mais.setText("+");
        btnG2Mais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG2MaisActionPerformed(evt);
            }
        });

        pnl2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnl2Layout = new javax.swing.GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnl2Layout.setVerticalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );

        txtR2.setEditable(false);
        txtR2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtR2.setText("255");

        sldRR.setMaximum(255);
        sldRR.setOrientation(javax.swing.JSlider.VERTICAL);
        sldRR.setValue(255);
        sldRR.setEnabled(false);
        sldRR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sldBRMouseEntered(evt);
            }
        });

        lblRR.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lblRR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRR.setText("R");

        sldGR.setMaximum(255);
        sldGR.setOrientation(javax.swing.JSlider.VERTICAL);
        sldGR.setValue(255);
        sldGR.setEnabled(false);
        sldGR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sldBRMouseEntered(evt);
            }
        });

        lblGR.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lblGR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGR.setText("G");

        txtGR.setEditable(false);
        txtGR.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtGR.setText("255");

        sldBR.setMaximum(255);
        sldBR.setOrientation(javax.swing.JSlider.VERTICAL);
        sldBR.setValue(255);
        sldBR.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sldBR.setEnabled(false);
        sldBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sldBRMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sldBRMouseExited(evt);
            }
        });

        lblBR.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lblBR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBR.setText("B");

        txtBR.setEditable(false);
        txtBR.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtBR.setText("255");

        txtRGBR.setEditable(false);
        txtRGBR.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtRGBR.setText("#FFFFFF");

        pnlR.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlRLayout = new javax.swing.GroupLayout(pnlR);
        pnlR.setLayout(pnlRLayout);
        pnlRLayout.setHorizontalGroup(
            pnlRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlRLayout.setVerticalGroup(
            pnlRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );

        txtRR.setEditable(false);
        txtRR.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtRR.setText("255");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnR1Mais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtR1)
                            .addComponent(sldR1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblR1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnR1Menos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnG1Mais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtG1)
                            .addComponent(lblG1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnG1Menos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sldG1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblB1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnB1Menos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtB1)
                            .addComponent(btnB1Mais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sldB1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRGB1)
                            .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnR2Mais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtR2)
                            .addComponent(sldR2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblR2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnR2Menos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnG2Mais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtG2)
                            .addComponent(sldG2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblG2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnG2Menos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sldB2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblB2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnB2Menos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtB2)
                            .addComponent(btnB3Mais))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRGB2, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRGBR, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(pnlR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRR)
                    .addComponent(sldRR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRR, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGR)
                    .addComponent(sldGR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGR, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sldBR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBR, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnR1Mais, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnG1Mais, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnB1Mais, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sldR1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblR1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sldG1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblG1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnG1Menos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnB1Menos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnR1Menos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtG1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(sldB1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblB1))
                                    .addComponent(pnl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRGB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnR2Mais, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnG2Mais, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnB3Mais, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sldR2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblR2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sldG2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblG2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnG2Menos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnB2Menos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnR2Menos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(sldB2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblB2))
                                    .addComponent(pnl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRGB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtG2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(sldRR, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblRR))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(sldGR, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblGR))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(sldBR, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblBR)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtBR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtGR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtRR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRGBR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtR1ActionPerformed

    private void btnR1MaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnR1MaisActionPerformed
        // TODO add your handling code here:
        sldR1.setValue(sldR1.getValue() + 1);
        Atualizar();
    }//GEN-LAST:event_btnR1MaisActionPerformed

    private void btnG1MaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG1MaisActionPerformed
        // TODO add your handling code here:
        sldG1.setValue(sldG1.getValue() + 1);
        Atualizar();
    }//GEN-LAST:event_btnG1MaisActionPerformed

    private void btnB1MaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB1MaisActionPerformed
        // TODO add your handling code here:
        sldB1.setValue(sldB1.getValue() + 1);
        Atualizar();
    }//GEN-LAST:event_btnB1MaisActionPerformed

    private void btnR1MenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnR1MenosActionPerformed
        // TODO add your handling code here:
        sldR1.setValue(sldR1.getValue() - 1);
        Atualizar();
    }//GEN-LAST:event_btnR1MenosActionPerformed

    private void btnG1MenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG1MenosActionPerformed
        // TODO add your handling code here:
        sldG1.setValue(sldG1.getValue() - 1);
        Atualizar();
    }//GEN-LAST:event_btnG1MenosActionPerformed

    private void btnB1MenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB1MenosActionPerformed
        // TODO add your handling code here:
        sldB1.setValue(sldB1.getValue() - 1);
        Atualizar();
    }//GEN-LAST:event_btnB1MenosActionPerformed

    private void sldR1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_sldR1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_sldR1PropertyChange

    private void sldR1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldR1MouseDragged
        // TODO add your handling code here:
        txtR1.setText(String.valueOf(sldR1.getValue()));
        Atualizar();
    }//GEN-LAST:event_sldR1MouseDragged

    private void sldG1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldG1MouseDragged
        // TODO add your handling code here:
        txtG1.setText(String.valueOf(sldG1.getValue()));
        Atualizar();
    }//GEN-LAST:event_sldG1MouseDragged

    private void sldB1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldB1MouseDragged
        // TODO add your handling code here:
        txtB1.setText(String.valueOf(sldB1.getValue()));
        Atualizar();
    }//GEN-LAST:event_sldB1MouseDragged

    private void sldR1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldR1MouseClicked
        // TODO add your handling code here:
        txtR1.setText(String.valueOf(sldR1.getValue()));
        Atualizar();
    }//GEN-LAST:event_sldR1MouseClicked

    private void sldG1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldG1MouseClicked
        // TODO add your handling code here:
        txtG1.setText(String.valueOf(sldG1.getValue()));
        Atualizar();
    }//GEN-LAST:event_sldG1MouseClicked

    private void sldB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldB1MouseClicked
        // TODO add your handling code here:
        txtB1.setText(String.valueOf(sldB1.getValue()));
        Atualizar();
    }//GEN-LAST:event_sldB1MouseClicked

    private void sldR1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldR1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_sldR1MouseMoved

    private void btnR2MaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnR2MaisActionPerformed
        // TODO add your handling code here:
        sldR2.setValue(sldR2.getValue() + 1);
        Atualizar();
    }//GEN-LAST:event_btnR2MaisActionPerformed

    private void btnG2MaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG2MaisActionPerformed
        // TODO add your handling code here:
        sldG2.setValue(sldG2.getValue() + 1);
        Atualizar();
    }//GEN-LAST:event_btnG2MaisActionPerformed

    private void btnB3MaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB3MaisActionPerformed
        // TODO add your handling code here:
        sldB2.setValue(sldB2.getValue() + 1);
        Atualizar();
    }//GEN-LAST:event_btnB3MaisActionPerformed

    private void sldR2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldR2MouseClicked
        // TODO add your handling code here:
        txtR2.setText(String.valueOf(sldR2.getValue()));
        Atualizar();
    }//GEN-LAST:event_sldR2MouseClicked

    private void sldR2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldR2MouseDragged
        // TODO add your handling code here:
        txtR2.setText(String.valueOf(sldR2.getValue()));
        Atualizar();
    }//GEN-LAST:event_sldR2MouseDragged

    private void sldG2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldG2MouseClicked
        // TODO add your handling code here:
        txtG2.setText(String.valueOf(sldG2.getValue()));
        Atualizar();
    }//GEN-LAST:event_sldG2MouseClicked

    private void sldG2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldG2MouseDragged
        // TODO add your handling code here:
        txtG2.setText(String.valueOf(sldG2.getValue()));
        Atualizar();
    }//GEN-LAST:event_sldG2MouseDragged

    private void sldB2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldB2MouseClicked
        // TODO add your handling code here:
        txtB2.setText(String.valueOf(sldB2.getValue()));
        Atualizar();
    }//GEN-LAST:event_sldB2MouseClicked

    private void sldB2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldB2MouseDragged
        // TODO add your handling code here:
        txtB2.setText(String.valueOf(sldB2.getValue()));
        Atualizar();
    }//GEN-LAST:event_sldB2MouseDragged

    private void btnR2MenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnR2MenosActionPerformed
        // TODO add your handling code here:
        sldR2.setValue(sldR2.getValue() - 1);
        Atualizar();
    }//GEN-LAST:event_btnR2MenosActionPerformed

    private void btnG2MenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG2MenosActionPerformed
        // TODO add your handling code here:
        sldG2.setValue(sldG2.getValue() - 1);
        Atualizar();
    }//GEN-LAST:event_btnG2MenosActionPerformed

    private void btnB2MenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB2MenosActionPerformed
        // TODO add your handling code here:
        sldB2.setValue(sldB2.getValue() - 1);
        Atualizar();
    }//GEN-LAST:event_btnB2MenosActionPerformed

    private void sldBRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldBRMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_sldBRMouseEntered

    private void sldBRMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldBRMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_sldBRMouseExited
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnB1Mais;
    private javax.swing.JButton btnB1Menos;
    private javax.swing.JButton btnB2Menos;
    private javax.swing.JButton btnB3Mais;
    private javax.swing.JButton btnG1Mais;
    private javax.swing.JButton btnG1Menos;
    private javax.swing.JButton btnG2Mais;
    private javax.swing.JButton btnG2Menos;
    private javax.swing.JButton btnR1Mais;
    private javax.swing.JButton btnR1Menos;
    private javax.swing.JButton btnR2Mais;
    private javax.swing.JButton btnR2Menos;
    private javax.swing.JLabel lblB1;
    private javax.swing.JLabel lblB2;
    private javax.swing.JLabel lblBR;
    private javax.swing.JLabel lblG1;
    private javax.swing.JLabel lblG2;
    private javax.swing.JLabel lblGR;
    private javax.swing.JLabel lblR1;
    private javax.swing.JLabel lblR2;
    private javax.swing.JLabel lblRR;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnlR;
    private javax.swing.JSlider sldB1;
    private javax.swing.JSlider sldB2;
    private javax.swing.JSlider sldBR;
    private javax.swing.JSlider sldG1;
    private javax.swing.JSlider sldG2;
    private javax.swing.JSlider sldGR;
    private javax.swing.JSlider sldR1;
    private javax.swing.JSlider sldR2;
    private javax.swing.JSlider sldRR;
    private javax.swing.JTextField txtB1;
    private javax.swing.JTextField txtB2;
    private javax.swing.JTextField txtBR;
    private javax.swing.JTextField txtG1;
    private javax.swing.JTextField txtG2;
    private javax.swing.JTextField txtGR;
    private javax.swing.JTextField txtR1;
    private javax.swing.JTextField txtR2;
    private javax.swing.JTextField txtRGB1;
    private javax.swing.JTextField txtRGB2;
    private javax.swing.JTextField txtRGBR;
    private javax.swing.JTextField txtRR;
    // End of variables declaration//GEN-END:variables
}
